"""Add media metadata fields for scanning

Revision ID: bf242ca44f6a
Revises: f7ececfd0ea6
Create Date: 2026-04-07 06:23:50.454966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bf242ca44f6a'
down_revision: Union[str, None] = 'f7ececfd0ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_constraint(None, 'stop', type_='foreignkey')
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stop', 'media_asset', ['cover_media_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'trip', 'media_asset', ['cover_media_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###
